FROM jenkins/jenkins:lts

USER root

# Install docker inside Jenkins container (optional but useful)
RUN apt-get update && \
    apt-get install -y docker.io && \
    usermod -aG docker jenkins

# Copy plugins.txt and install plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

USER jenkins
